name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: DoubleFours.sln
      DotNet_Version: 6.0.x  # Specify the desired .NET Core version here

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DotNet_Version }}

      - name: Build the application
        run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }}

      - name: Publish the application
        run: dotnet publish ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --output ${{ env.Solution_Name }}/publish

      - name: Get Commit Information
        id: commit_info
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD) ::set-output name=message::$(git log -1 --pretty=format:'%s')"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.commit_info.outputs.hash }}
          release_name: Release ${{ steps.commit_info.outputs.hash }}
          body: |
            Commit Hash: ${{ steps.commit_info.outputs.hash }}
            Commit Message: ${{ steps.commit_info.outputs.message }}

            Release Notes for ${{ steps.commit_info.outputs.hash }}
          draft: false
          prerelease: false

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: App Package
          path: ${{ env.Solution_Name }}/publish/*
